setGeneric("revmap", function(x, mapName=NULL) standardGeneric("revmap"))
setGeneric("db", function(object) standardGeneric("db"))
setGeneric("nrow", function(x) standardGeneric("nrow"))
setGeneric("left.names", function(x) standardGeneric("left.names"))
setGeneric("right.names", function(x) standardGeneric("right.names"))
setGeneric("left.length", function(x) standardGeneric("left.length"))
setGeneric("right.length", function(x) standardGeneric("right.length"))
setGeneric("mapped.left.names", function(x) standardGeneric("mapped.left.names"))
setGeneric("count.mapped.left.names", function(x) standardGeneric("count.mapped.left.names"))
setGeneric("mapped.right.names", function(x) standardGeneric("mapped.right.names"))
setGeneric("count.mapped.right.names", function(x) standardGeneric("count.mapped.right.names"))
setGeneric("mapped.names", function(x) standardGeneric("mapped.names"))
setGeneric("count.mapped.names", function(x) standardGeneric("count.mapped.names"))
