### Bimap interface
### (Please don't sort this section in alphabetical order)
setGeneric("colmetanames", function(x) standardGeneric("colmetanames"))
setGeneric("Lkeyname", function(x) standardGeneric("Lkeyname"))
setGeneric("Rkeyname", function(x) standardGeneric("Rkeyname"))
setGeneric("tagname", function(x) standardGeneric("tagname"))
setGeneric("Rattribnames", function(x) standardGeneric("Rattribnames"))
setGeneric("direction", function(x) standardGeneric("direction"))
setGeneric("direction<-", signature="x", function(x, value) standardGeneric("direction<-"))
setGeneric("revmap", function(x, ...) standardGeneric("revmap"))
setGeneric("Lkeys", function(x) standardGeneric("Lkeys"))
setGeneric("Rkeys", function(x) standardGeneric("Rkeys"))
setGeneric("Lkeys<-", signature="x", function(x, value) standardGeneric("Lkeys<-"))
setGeneric("Rkeys<-", signature="x", function(x, value) standardGeneric("Rkeys<-"))
setGeneric("mappedLkeys", function(x) standardGeneric("mappedLkeys"))
setGeneric("mappedRkeys", function(x) standardGeneric("mappedRkeys"))
setGeneric("edges", function(x) standardGeneric("edges"))
setGeneric("toLList", signature="x", function(x, keys=NULL) standardGeneric("toLList"))
setGeneric("toRList", signature="x", function(x, keys=NULL) standardGeneric("toRList"))
setGeneric("Llength", function(x) standardGeneric("Llength"))
setGeneric("Rlength", function(x) standardGeneric("Rlength"))
setGeneric("count.mappedLkeys", function(x) standardGeneric("count.mappedLkeys"))
setGeneric("count.mappedRkeys", function(x) standardGeneric("count.mappedRkeys"))
setGeneric("count.edges", function(x) standardGeneric("count.edges"))
setGeneric("from.colpos", signature="x", function(x, direction) standardGeneric("from.colpos"))
setGeneric("to.colpos", signature="x", function(x, direction) standardGeneric("to.colpos"))
setGeneric("tags.colpos", function(x) standardGeneric("tags.colpos"))
setGeneric("from.keys", signature="x", function(x, direction) standardGeneric("from.keys"))
setGeneric("to.keys", signature="x", function(x, direction) standardGeneric("to.keys"))
setGeneric("keys", function(x) standardGeneric("keys"))
setGeneric("keys<-", signature="x", function(x, value) standardGeneric("keys<-"))
setGeneric("mappedkeys", function(x) standardGeneric("mappedkeys"))
setGeneric("count.mappedkeys", function(x) standardGeneric("count.mappedkeys"))
setGeneric("toList", signature="x", function(x, keys=NULL) standardGeneric("toList"))

### Others (do whatever you want with them ;-)
setGeneric("db", function(object) standardGeneric("db"))
setGeneric("Ltablename", function(x) standardGeneric("Ltablename"))
setGeneric("Rtablename", function(x) standardGeneric("Rtablename"))
setGeneric("Lfilter", function(x) standardGeneric("Lfilter"))
setGeneric("Rfilter", function(x) standardGeneric("Rfilter"))
setGeneric("flatten", function(x, ...) standardGeneric("flatten"))
setGeneric("toTable", signature="x", function(x, Lkeys=NULL, Rkeys=NULL) standardGeneric("toTable"))

