### BimapAPI0 interface
### (Please don't sort this section in alphabetical order)
setGeneric("collabels", function(x) standardGeneric("collabels"))
setGeneric("left.names", function(x) standardGeneric("left.names"))
setGeneric("right.names", function(x) standardGeneric("right.names"))
setGeneric("left.mappedNames", function(x) standardGeneric("left.mappedNames"))
setGeneric("right.mappedNames", function(x) standardGeneric("right.mappedNames"))
setGeneric("links", function(x) standardGeneric("links"))
setGeneric("left.length", function(x) standardGeneric("left.length"))
setGeneric("right.length", function(x) standardGeneric("right.length"))
setGeneric("count.left.mappedNames", function(x) standardGeneric("count.left.mappedNames"))
setGeneric("count.right.mappedNames", function(x) standardGeneric("count.right.mappedNames"))
setGeneric("count.links", function(x) standardGeneric("count.links"))
setGeneric("left.colname", function(x) standardGeneric("left.colname"))
setGeneric("right.colname", function(x) standardGeneric("right.colname"))
setGeneric("from.colpos", function(x, direction) standardGeneric("from.colpos"))
setGeneric("to.colpos", function(x, direction) standardGeneric("to.colpos"))
setGeneric("tags.colpos", function(x) standardGeneric("tags.colpos"))
setGeneric("from.names", function(x, direction) standardGeneric("from.names"))
setGeneric("to.names", function(x, direction) standardGeneric("to.names"))

### Others (do whatever you want with them ;-)
setGeneric("count.mappedNames", function(x) standardGeneric("count.mappedNames"))
setGeneric("db", function(object) standardGeneric("db"))
setGeneric("flatten", function(x, left.names, right.names, ...) standardGeneric("flatten"))
setGeneric("left.filter", function(x) standardGeneric("left.filter"))
setGeneric("left.table", function(x) standardGeneric("left.table"))
setGeneric("mappedNames", function(x) standardGeneric("mappedNames"))
setGeneric("revmap", function(x, objName=NULL) standardGeneric("revmap"))
setGeneric("right.filter", function(x) standardGeneric("right.filter"))
setGeneric("right.table", function(x) standardGeneric("right.table"))
setGeneric("toList", function(x, names=NULL) standardGeneric("toList"))
setGeneric("toTable", function(x, ...) standardGeneric("toTable"))

